%YAML 1.2
%TAG !n! tag:nimyaml.org,2016:
--- !n!custom:MonitorConfig 
sleep: 1
targets: 
  - 
    name: Run tests
    paths: [src, tests]
    commands:
      - nimble test
      - nimble test --gcc.path:D:\mingw32\bin\ --cpu:i386
    extensions: [.nim]
    files: []
    exclude_extensions: []
    exclude_files: []
    once: true
